# Generated by Django 5.1 on 2024-09-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.FileField(blank=True, null=True, upload_to='store/'),
        ),
    ]
